[repos]
customer-config = "staging:dev"
enterprise      = "17.0:shared+readonly"
odoo            = "17.0:shared+readonly"

[database]
name    = "staging"
pg_port = 5432

[server]
http_port   = 8106
gevent_port = 8107

[scripts]
default = "setup"

[scripts.runners.setup]
file = "setup.py"
type = "odoo_test"
